FROM node:24-alpine
WORKDIR /app
# Copy only package files first to leverage Docker cache
COPY package*.json ./
RUN npm install
# Copy the rest of the code
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]